export type Context = {
  readonly isPreviewMode: boolean;
  readonly getChatbotId: () => string;
  readonly getChatbotUserId: () => string;
  readonly hasInteractedWithChatbot: () => boolean;
  readonly getConfig: () => Config;
};

export type Config = {
  readonly purchaseTrackingEnabled: boolean;
  readonly checkoutConfirmationPagePatterns?: string;
  readonly checkoutPagePatterns?: string;
  readonly checkoutPriceSelector?: string;
  readonly checkoutPurchaseSelector?: string;
  readonly currency?: string;
  readonly themeColor?: string;
  readonly productButtonColor?: string;
  readonly zIndex?: number;
  readonly buttonRight?: string;
  readonly buttonBottom?: string;
  readonly chatButtonImageUrl?: string;
  readonly iframeUrl?: string;
  readonly previewMode?: string;
  readonly iframeWidthEnlarged?: string;
  readonly iframeHeightEnlarged?: string;
  readonly iframeWidthMobile?: string;
  readonly iframeHeightMobile?: string;
  readonly iframeWidthDesktop?: string;
  readonly iframeHeightDesktop?: string;
  readonly popupShowOnMobile?: boolean;
  readonly popupMaxDisplays?: number;
  readonly borderRadiusMultiplier?: number;
  readonly leadMail?: string;
  readonly toHumanMail?: string;
  readonly freshdeskGroupId?: string;
  readonly enablePopupMessage: boolean;
  readonly enableMinimizeButton: boolean;
  readonly fontFamily?: string;
  readonly pagePath?: string;
  readonly isPhoneView: boolean;
  readonly headerTitleG?: string;
  readonly headerSubtitleG?: string;
  readonly titleG?: string;
  readonly leadGen?: string;
  readonly leadField1?: string;
  readonly leadField2?: string;
  readonly useThumbsRating: boolean;
  readonly ratingTimerDuration?: number;
  readonly replaceExclamationWithPeriod: boolean;
  readonly privacyLink?: string;
  readonly freshdeskEmailLabel?: string;
  readonly freshdeskMessageLabel?: string;
  readonly freshdeskImageLabel?: string;
  readonly freshdeskChooseFileText?: string;
  readonly freshdeskNoFileText?: string;
  readonly freshdeskSendingText?: string;
  readonly freshdeskSubmitText?: string;
  readonly freshdeskEmailRequiredError?: string;
  readonly freshdeskEmailInvalidError?: string;
  readonly freshdeskFormErrorText?: string;
  readonly freshdeskMessageRequiredError?: string;
  readonly freshdeskSubmitErrorText?: string;
  readonly contactConfirmationText?: string;
  readonly freshdeskConfirmationText?: string;
  readonly freshdeskSubjectText?: string;
  readonly inputPlaceholder?: string;
  readonly ratingMessage?: string;
  readonly productButtonText?: string;
  readonly productButtonPadding?: string;
  readonly productImageHeightMultiplier?: number;
  readonly headerLogoG?: string;
  readonly messageIcon?: string;
  readonly aiMessageColor?: string;
  readonly aiMessageTextColor?: string;
  readonly subtitleLinkText?: string;
  readonly subtitleLinkUrl?: string;
  readonly enableLivechat: boolean;
  readonly require_email_before_conversation?: boolean;
  readonly splitTestId?: string | null;
  readonly isTabletView: boolean;
};
