export type Context = {
  readonly isPreviewMode: boolean,
  readonly chatbotID: string,
  readonly chatbotUserId: string,
  readonly isIframeEnlarged: boolean,
  readonly hasReportedPurchase: boolean,
  readonly hasInteractedWithChatbot: boolean,
  readonly config: {
    readonly purchaseTrackingEnabled: boolean,
    readonly checkoutConfirmationPagePatterns?: string,
    readonly checkoutPagePatterns?: string,
    readonly checkoutPriceSelector?: string,
    readonly checkoutPurchaseSelector?: string,
    readonly currency?: string;
    readonly themeColor?: string,
    readonly productButtonColor?: string,
    readonly zIndex?: number,
    readonly buttonRight?: string,
    readonly buttonBottom?: string,
    readonly chatButtonImageUrl?: string,
    readonly iframeUrl?: string,
    readonly previewMode?: string,
    readonly iframeWidthEnlarged?: string,
    readonly iframeHeightEnlarged?: string,
    readonly iframeWidthMobile?: string,
    readonly iframeHeightMobile?: string,
    readonly iframeWidthDesktop?: string,
    readonly iframeHeightDesktop?: string,
    readonly popupShowOnMobile?: boolean,
    readonly popupMaxDisplays?: number,
  },
}
